import { Prisma } from 'prisma-binding'

const prisma = new Prisma({
    typeDefs: 'src/generated/prisma.graphql',
    endpoint: 'http://localhost:4466',
    secret: 'd7e01978-66b3-4614-a4e5-f13c19af590e'
})

/*
token generated by "prisma token"
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InNlcnZpY2UiOiJkZWZhdWx0QGRlZmF1bHQiLCJyb2xlcyI6WyJhZG1pbiJdfSwiaWF0IjoxNTU2Njg2NDU0LCJleHAiOjE1NTcyOTEyNTR9.nWrwTG6fgAN6YNaxQsZUvMhhmJ3_59MnIwmOoXxyZm8
*/

export { prisma as default }